export const feedSchema = [
  {
    id: 1,
    headTitle: 'Сказочное заморское яство',
    brand: 'Нямушка',
    feedLabel: 'с фуа-гра',
    additionalLabel: 'Печень утки разварная с артишоками.',
    weight: '0,5',
    portion: '10 порций',
    presents: 'мышь в подарок',
    balance: 10,
    reviews: '',
  },
  {
    id: 2,
    headTitle: 'Сказочное заморское яство',
    brand: 'Нямушка',
    feedLabel: 'с рыбой',
    additionalLabel: 'Головы щучьи с чесноком да свежайшая сёмгушка.',
    weight: '2',
    portion: '40 порций',
    presents: '2 мыши в подарок',
    balance: 20,
    reviews: '',
  },
  {
    id: 3,
    headTitle: 'Сказочное заморское яство',
    brand: 'Нямушка',
    feedLabel: 'с курой',
    additionalLabel: 'Филе из цыплят с трюфелями в бульоне.',
    weight: '5',
    portion: '100 порций',
    presents: '5 мышей в подарок',
    balance: 0,
    reviews: 'заказчик доволен',
  },
];
